name: GameAPI
version: 1.0
main: xyz.jadonfowler.gameapi.GameAPI
authors: [jadonfowler, Bevelio]
description: An API above all APIs.
commands:
  hub:
    description: Teleports you back to the hub.
  game:
    description: Spawns a mob to join a game
